INSERT INTO DrinkKind (id,name,updatedAt) VALUES
(0,'ジン',datetime('now', 'localtime')),
(1,'ウォッカ',datetime('now', 'localtime')),
(2,'ラム',datetime('now', 'localtime')),
(3,'テキーラ',datetime('now', 'localtime')),
(4,'ウイスキー',datetime('now', 'localtime')),
(5,'ブランデー',datetime('now', 'localtime')),
(6,'ココナッツリキュール (マリブ)',datetime('now', 'localtime')),
(7,'コーヒーリキュール (カルーア)',datetime('now', 'localtime')),
(8,'マンゴーリキュール (マンゴヤン)',datetime('now', 'localtime')),
(9,'ライチリキュール',datetime('now', 'localtime')),
(10,'カシスリキュール',datetime('now', 'localtime')),
(11,'ピーチリキュール',datetime('now', 'localtime')),
(12,'ホワイトキュラソー (コアントロー)',datetime('now', 'localtime')),
(13,'オレンジキュラソー',datetime('now', 'localtime')),
(14,'ブルーキュラソー',datetime('now', 'localtime')),
(15,'ヨーグルトリキュール',datetime('now', 'localtime')),
(16,'アプリコットリキュール',datetime('now', 'localtime')),
(17,'アマレット',datetime('now', 'localtime')),
(18,'カンパリ',datetime('now', 'localtime')),
(19,'イエーガーマイスター',datetime('now', 'localtime')),
(20,'チョコレートリキュール',datetime('now', 'localtime')),
(21,'カカオリキュール',datetime('now', 'localtime')),
(22,'チェリーリキュール',datetime('now', 'localtime')),
(23,'メロンリキュール (ミドリ)',datetime('now', 'localtime')),
(24,'フランボワーズリキュール',datetime('now', 'localtime')),
(25,'バナナリキュール',datetime('now', 'localtime')),
(26,'サザンカンフォート (フルーツリキュール)',datetime('now', 'localtime')),
(27,'パッションフルーツリキュール (パッソア)',datetime('now', 'localtime')),
(28,'ミントリキュール',datetime('now', 'localtime')),
(29,'紅茶リキュール',datetime('now', 'localtime')),
(30,'パルフェタムール (バイオレットリキュール)',datetime('now', 'localtime')),
(31,'クリームリキュール (ベイリーズ)',datetime('now', 'localtime')),
(32,'マスカットリキュール (ミスティア)',datetime('now', 'localtime')),
(33,'スロージン (スローベリーリキュール)',datetime('now', 'localtime')),
(34,'ピンクグレープフルーツリキュール',datetime('now', 'localtime')),
(35,'ストロベリーリキュール',datetime('now', 'localtime')),
(36,'マラスキーノリキュール (ルクサルド)',datetime('now', 'localtime')),
(37,'卵リキュール (アドヴォカート)',datetime('now', 'localtime')),
(38,'プラムリキュール (プルシア)',datetime('now', 'localtime')),
(39,'ガリアーノ',datetime('now', 'localtime')),
(40,'アブサン',datetime('now', 'localtime')),
(41,'ヘーゼルナッツリキュール',datetime('now', 'localtime')),
(42,'ドランブイ',datetime('now', 'localtime')),
(43,'ベネディクティン',datetime('now', 'localtime')),
(44,'コカリキュール (コカレロ)',datetime('now', 'localtime')),
(45,'アロマティックビターズ',datetime('now', 'localtime')),
(46,'オレンジビターズ',datetime('now', 'localtime')),
(47,'白ワイン',datetime('now', 'localtime')),
(48,'赤ワイン',datetime('now', 'localtime')),
(49,'ロゼワイン',datetime('now', 'localtime')),
(50,'ポートワイン',datetime('now', 'localtime')),
(51,'スパークリングワイン (シャンパン)',datetime('now', 'localtime')),
(52,'スイート・ベルモット',datetime('now', 'localtime')),
(53,'ドライ・ベルモット',datetime('now', 'localtime')),
(54,'ビール',datetime('now', 'localtime')),
(55,'日本酒',datetime('now', 'localtime')),
(56,'焼酎',datetime('now', 'localtime')),
(57,'梅酒',datetime('now', 'localtime')),
(58,'ソーダ',datetime('now', 'localtime')),
(59,'トニックウォーター',datetime('now', 'localtime')),
(60,'水',datetime('now', 'localtime')),
(61,'砂糖',datetime('now', 'localtime')),
(62,'シュガーシロップ (ガムシロップ)',datetime('now', 'localtime')),
(63,'グレナデンシロップ',datetime('now', 'localtime')),
(64,'レモンジュース',datetime('now', 'localtime')),
(65,'ライムジュース',datetime('now', 'localtime')),
(66,'オレンジジュース',datetime('now', 'localtime')),
(67,'パイナップルジュース',datetime('now', 'localtime')),
(68,'グレープフルーツジュース',datetime('now', 'localtime')),
(69,'アップルジュース',datetime('now', 'localtime')),
(70,'マンゴージュース',datetime('now', 'localtime')),
(71,'グレープジュース (ぶどうジュース)',datetime('now', 'localtime')),
(72,'ピーチジュース',datetime('now', 'localtime')),
(73,'アセロラジュース',datetime('now', 'localtime')),
(74,'トマトジュース (食塩無添加)',datetime('now', 'localtime')),
(75,'コーヒー',datetime('now', 'localtime')),
(76,'エスプレッソ・コーヒー',datetime('now', 'localtime')),
(77,'インスタントコーヒー',datetime('now', 'localtime')),
(78,'紅茶',datetime('now', 'localtime')),
(79,'烏龍茶',datetime('now', 'localtime')),
(80,'ジャスミン茶',datetime('now', 'localtime')),
(81,'緑茶',datetime('now', 'localtime')),
(82,'コーラ',datetime('now', 'localtime')),
(83,'ジンジャーエール',datetime('now', 'localtime')),
(84,'スプライト',datetime('now', 'localtime')),
(85,'エナジードリンク',datetime('now', 'localtime')),
(86,'クランベリージュース',datetime('now', 'localtime')),
(87,'牛乳',datetime('now', 'localtime')),
(88,'豆乳',datetime('now', 'localtime')),
(89,'ココナッツミルク',datetime('now', 'localtime')),
(90,'ヨーグルト',datetime('now', 'localtime')),
(91,'バニラエッセンス',datetime('now', 'localtime')),
(92,'生クリーム',datetime('now', 'localtime')),
(93,'全卵',datetime('now', 'localtime')),
(94,'卵黄',datetime('now', 'localtime')),
(95,'卵白',datetime('now', 'localtime')),
(96,'蜂蜜',datetime('now', 'localtime')),
(97,'巨峰 (ぶどう)',datetime('now', 'localtime')),
(98,'シナモン',datetime('now', 'localtime')),
(99,'ナツメグ',datetime('now', 'localtime'));

INSERT INTO DrinkKind (id,name,updatedAt) VALUES
(100,'抹茶パウダー',datetime('now', 'localtime')),
(101,'バニラアイスクリーム',datetime('now', 'localtime')),
(102,'カシスシロップ',datetime('now', 'localtime')),
(103,'マンゴーシロップ',datetime('now', 'localtime')),
(104,'巨峰シロップ',datetime('now', 'localtime')),
(105,'ライチシロップ',datetime('now', 'localtime')),
(106,'ピーチシロップ',datetime('now', 'localtime')),
(107,'ココナッツシロップ',datetime('now', 'localtime')),
(108,'チョコレートシロップ',datetime('now', 'localtime')),
(109,'アマレットシロップ',datetime('now', 'localtime')),
(110,'ブルーキュラソーシロップ',datetime('now', 'localtime')),
(111,'グリーンアップルシロップ',datetime('now', 'localtime')),
(112,'キャラメルシロップ',datetime('now', 'localtime')),
(113,'カルピス (原液)',datetime('now', 'localtime')),
(114,'スイート＆サワーミックス',datetime('now', 'localtime')),
(115,'塩',datetime('now', 'localtime')),
(116,'レモン',datetime('now', 'localtime')),
(117,'ライム',datetime('now', 'localtime')),
(118,'バナナ',datetime('now', 'localtime')),
(119,'苺',datetime('now', 'localtime')),
(120,'バター (無塩)',datetime('now', 'localtime')),
(121,'胡椒',datetime('now', 'localtime')),
(122,'ココアパウダー',datetime('now', 'localtime')),
(123,'ココナッツパウダー',datetime('now', 'localtime')),
(124,'ミントの葉',datetime('now', 'localtime')),
(125,'オリーブ',datetime('now', 'localtime')),
(126,'チェリー',datetime('now', 'localtime')),
(127,'パイナップル',datetime('now', 'localtime')),
(128,'オレンジ',datetime('now', 'localtime')),
(129,'グレープフルーツ',datetime('now', 'localtime')),
(130,'りんご',datetime('now', 'localtime')),
(131,'ラズベリー',datetime('now', 'localtime')),
(132,'トマト',datetime('now', 'localtime')),
(133,'きゅうり',datetime('now', 'localtime')),
(134,'チョコレート',datetime('now', 'localtime')),
(135,'アーモンド',datetime('now', 'localtime')),
(136,'パールオニオン',datetime('now', 'localtime')),
(137,'梅酒の梅の実',datetime('now', 'localtime')),
(138,'金粉',datetime('now', 'localtime'));