INSERT INTO Glass (id,name,updatedAt) VALUES
(0,'タンブラー',datetime('now', 'localtime')),
(1,'カクテルグラス',datetime('now', 'localtime')),
(2,'オールドファッションドグラス (ロックグラス)',datetime('now', 'localtime')),
(3,'ソーサー型シャンパングラス',datetime('now', 'localtime')),
(4,'コリンズグラス',datetime('now', 'localtime')),
(5,'ゴブレット',datetime('now', 'localtime')),
(6,'サワーグラス',datetime('now', 'localtime')),
(7,'耐熱グラス',datetime('now', 'localtime')),
(8,'フルート型シャンパングラス',datetime('now', 'localtime')),
(9,'トロピカルグラス',datetime('now', 'localtime')),
(10,'ショットグラス',datetime('now', 'localtime')),
(11,'ブランデーグラス',datetime('now', 'localtime')),
(12,'',datetime('now', 'localtime')),
(13,'リキュールグラス',datetime('now', 'localtime')),
(14,'ワイングラス',datetime('now', 'localtime')),
(15,'タンブラー, ショットグラス',datetime('now', 'localtime')),
(16,'アブサングラス',datetime('now', 'localtime')),
(17,'ピルスナーグラス',datetime('now', 'localtime')),
(18,'ボムグラス',datetime('now', 'localtime'));